apiVersion: v1
kind: Service
metadata:
  name: odoo
  labels:
    {{- include "op.componentLabels" (list . "odoo") | nindent 4 }}
spec:
  selector:
    {{- include "op.selector" (list . "odoo") | nindent 4 }}
  ports:
    - name: http
      port: 8069
      targetPort: http
    - name: websocket
      port: 8072
      targetPort: websocket
