{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    {{- include "op.componentLabels" (list . "keycloak") | nindent 4 }}
spec:
  selector:
    {{- include "op.selector" (list . "keycloak") | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: management
      port: 9000
      targetPort: management
{{- end }}
